# Use a base image
FROM scratch

ENV WASMEDGE_PLUGIN_PATH=${WASMEDGE_PLUGIN_PATH:-"/usr/lib/wasmedge"}
ENV WASMEDGE_WASINN_PRELOAD=${WASMEDGE_WASINN_PRELOAD:-"default:GGML:AUTO:/app/model.gguf"}

WORKDIR /work

# Copy wasm files to the directory
COPY llama-chat.wasm /work

# COPY model.gguf /app
ENTRYPOINT ["/work/llama-chat.wasm"]